apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: monitoring:node-exporter
roleRef:
  kind: ClusterRole
  name: monitoring:node-exporter
subjects:
- kind: ServiceAccount
  name: node-exporter
  namespace: monitoring
userNames:
- system:serviceaccount:monitoring:node-exporter
